// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gnnmljvgvcsinflxvrso.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdubm1sanZndmNzaW5mbHh2cnNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNzk1OTIsImV4cCI6MjA1ODg1NTU5Mn0.qKdzXY6VV2AlPLPHLI4tkOv5XMgILGXa4EaHdMBo0S0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);